import type { ProjectSpec } from './types';

export const SAMPLE_SCRIPT = `AI를 활용하면 강의 영상 제작 과정을 훨씬 단순하게 만들 수 있습니다.
먼저 강의 대본을 작성하고, ChatGPT가 시각화가 필요한 구간을 분석합니다. 그다음 프로그램이 장면별 HTML을 생성하고 브라우저에서 결과를 확인합니다.
예전에는 모션그래픽 한 장면을 만드는 데 3시간이 걸렸지만, 자동화하면 약 30분으로 줄일 수 있습니다.
테스트 결과 대본 분석 시간은 70%, 반복 편집은 82%, 전체 제작 시간은 65% 감소했습니다.
기존 방식은 장면마다 처음부터 디자인해야 하지만 자동 방식은 검증된 구성 요소를 조합합니다.
마지막으로 원본 대본 연결, 클릭 단계 확인, HTML 저장 여부를 점검하세요.`;

export const SAMPLE_PROJECT: ProjectSpec = {
  schemaVersion: '1.0.0',
  catalogVersion: '1.0.0',
  project: {
    projectId: 'ai-lecture-demo',
    title: 'AI 강의 영상 제작 자동화',
    locale: 'ko-KR',
    aspectRatio: '16:9',
    designPreset: 'lecture-modern',
  },
  segments: [
    {
      segmentId: 'segment_01',
      sourceText: '먼저 강의 대본을 작성하고, ChatGPT가 시각화가 필요한 구간을 분석합니다. 그다음 프로그램이 장면별 HTML을 생성하고 브라우저에서 결과를 확인합니다.',
      startTime: '00:18',
      endTime: '00:28',
      recommendedMedia: 'MOTION',
      selectionReason: '연속된 제작 과정을 단계별로 보여주면 이해하기 쉽습니다.',
    },
    {
      segmentId: 'segment_02',
      sourceText: '예전에는 모션그래픽 한 장면을 만드는 데 3시간이 걸렸지만, 자동화하면 약 30분으로 줄일 수 있습니다.',
      startTime: '00:42',
      endTime: '00:50',
      recommendedMedia: 'MOTION',
      selectionReason: '시간 차이를 큰 숫자로 대비하면 효과가 큽니다.',
    },
    {
      segmentId: 'segment_03',
      sourceText: '테스트 결과 대본 분석 시간은 70%, 반복 편집은 82%, 전체 제작 시간은 65% 감소했습니다.',
      startTime: '01:02',
      endTime: '01:12',
      recommendedMedia: 'MOTION',
      selectionReason: '여러 수치를 순서대로 강조할 수 있습니다.',
    },
  ],
  scenes: [
    {
      sceneId: 'scene_001',
      segmentId: 'segment_01',
      title: 'AI 강의 영상 제작 흐름',
      sourceText: '대본 작성, AI 분석, HTML 생성, 브라우저 확인 순서로 진행합니다.',
      startTime: '00:18',
      endTime: '00:28',
      duration: 10,
      visualIntent: '복잡해 보이는 제작 과정을 네 단계로 단순화합니다.',
      visualGrammar: 'PROCESS',
      renderMode: 'STANDARD',
      composition: {
        layoutStrategy: 'horizontal_process',
        background: 'dark_grid',
      },
      content: {
        title: '강의 영상이 완성되는 과정',
        eyebrow: 'AI LECTURE WORKFLOW',
        steps: [
          { title: '대본 입력', description: '강의 전체 내용을 입력', icon: '01' },
          { title: 'AI 분석', description: '시각화 구간을 자동 선정', icon: '02' },
          { title: 'HTML 생성', description: 'Component를 조합해 제작', icon: '03' },
          { title: '녹화·활용', description: '브라우저에서 바로 재생', icon: '04' },
        ],
      },
      motionSequence: [
        { stepId: 'step_01', order: 1, atMs: 0, label: '첫 단계', actions: [{ type: 'enter', targetId: 'step-1', motion: 'pop' }] },
        { stepId: 'step_02', order: 2, atMs: 1500, label: '연결선', actions: [{ type: 'connect', targetId: 'connector-1', motion: 'drawLine' }] },
        { stepId: 'step_03', order: 3, atMs: 2600, label: '두 번째 단계', actions: [{ type: 'enter', targetId: 'step-2', motion: 'pop' }] },
        { stepId: 'step_04', order: 4, atMs: 3800, label: '세 번째 단계', actions: [{ type: 'enter', targetId: 'step-3', motion: 'pop' }] },
        { stepId: 'step_05', order: 5, atMs: 5200, label: '네 번째 단계', actions: [{ type: 'enter', targetId: 'step-4', motion: 'impact' }] },
      ],
      interaction: { mode: 'CLICK' },
      sound: ['pop', 'line', 'pop', 'whoosh', 'success'],
    },
    {
      sceneId: 'scene_002',
      segmentId: 'segment_02',
      title: '3시간에서 30분으로',
      sourceText: '예전에는 모션그래픽 한 장면을 만드는 데 3시간이 걸렸지만, 자동화하면 약 30분으로 줄일 수 있습니다.',
      startTime: '00:42',
      endTime: '00:50',
      duration: 8,
      visualIntent: '작업 시간이 압축되는 체감을 큰 숫자로 전달합니다.',
      visualGrammar: 'TIME_COMPRESSION',
      renderMode: 'CREATIVE',
      composition: {
        layoutStrategy: 'center_focus',
        background: 'navy_grid',
      },
      content: {
        title: '모션그래픽 제작 시간',
        eyebrow: 'TIME COMPRESSION',
        startValue: '3시간',
        startLabel: '기존 제작 방식',
        endValue: '30분',
        endLabel: 'AI 자동 생성',
        conclusion: '제작 시간을 1/6로 단축',
      },
      motionSequence: [
        { step: 1, atMs: 0, action: 'titleAppear' },
        { step: 2, atMs: 1200, action: 'startValueAppear' },
        { step: 3, atMs: 2600, action: 'timeCompress' },
        { step: 4, atMs: 4200, action: 'targetImpact' },
      ],
      interaction: { mode: 'CLICK' },
      sound: ['pop', 'tick', 'whoosh', 'impact'],
    },
    {
      sceneId: 'scene_003',
      segmentId: 'segment_03',
      title: '제작 시간 감소 효과',
      sourceText: '대본 분석 시간은 70%, 반복 편집은 82%, 전체 제작 시간은 65% 감소했습니다.',
      startTime: '01:02',
      endTime: '01:12',
      duration: 10,
      visualIntent: '자동화 효과를 세 개의 핵심 통계로 보여줍니다.',
      visualGrammar: 'STATISTICS',
      renderMode: 'STANDARD',
      composition: {
        layoutStrategy: 'three_cards',
        background: 'light_grid',
      },
      content: {
        title: '반복 작업이 눈에 띄게 줄었습니다',
        eyebrow: 'PRODUCTION RESULTS',
        items: [
          { label: '대본 분석 시간', value: 70, unit: '% 감소', icon: 'A' },
          { label: '반복 편집 작업', value: 82, unit: '% 감소', icon: 'B' },
          { label: '전체 제작 시간', value: 65, unit: '% 감소', icon: 'C' },
        ],
        conclusion: '강사는 내용 전달과 녹화에 집중할 수 있습니다.',
      },
      motionSequence: [
        { step: 1, atMs: 0, action: 'firstCard' },
        { step: 2, atMs: 1700, action: 'secondCard' },
        { step: 3, atMs: 3400, action: 'thirdCard' },
        { step: 4, atMs: 5400, action: 'conclusion' },
      ],
      interaction: { mode: 'TIMED' },
      sound: ['pop', 'pop', 'pop', 'success'],
    },
    {
      sceneId: 'scene_004',
      segmentId: 'segment_04',
      title: '기존 방식과 자동 방식',
      sourceText: '기존 방식은 장면마다 처음부터 디자인해야 하지만 자동 방식은 검증된 구성 요소를 조합합니다.',
      startTime: '01:25',
      endTime: '01:34',
      duration: 9,
      visualIntent: '두 제작 방식의 차이를 명확하게 대비합니다.',
      visualGrammar: 'COMPARISON',
      renderMode: 'STANDARD',
      composition: { layoutStrategy: 'split_compare', background: 'light_grid' },
      content: {
        title: '매번 새로 제작할 필요가 없습니다',
        left: { label: '기존 방식', value: '장면마다 디자인부터 다시 시작', points: ['긴 제작 시간', '품질 편차', '반복 작업'] },
        right: { label: '자동 방식', value: '검증된 Component를 자동 조합', points: ['빠른 생성', '일관된 품질', '선택 수정'] },
        conclusion: '반복 제작은 시스템에게, 설명은 강사에게',
      },
      motionSequence: [
        { step: 1, atMs: 0, action: 'leftAppear' },
        { step: 2, atMs: 1800, action: 'versus' },
        { step: 3, atMs: 3100, action: 'rightAppear' },
        { step: 4, atMs: 5200, action: 'conclusion' },
      ],
      interaction: { mode: 'CLICK' },
      sound: ['pop', 'whoosh', 'pop', 'impact'],
    },
    {
      sceneId: 'scene_005',
      segmentId: 'segment_05',
      title: '최종 점검',
      sourceText: '마지막으로 원본 대본 연결, 클릭 단계 확인, HTML 저장 여부를 점검하세요.',
      startTime: '01:48',
      endTime: '01:57',
      duration: 9,
      visualIntent: '완료 전에 확인할 항목을 기억하게 합니다.',
      visualGrammar: 'CHECKLIST',
      renderMode: 'STANDARD',
      composition: { layoutStrategy: 'stacked_checklist', background: 'navy_grid' },
      content: {
        title: '녹화 전 마지막 체크',
        eyebrow: 'FINAL CHECK',
        items: ['원본 대본 구간이 정확한가?', '클릭 한 번에 한 단계만 실행되는가?', '모든 장면 HTML이 저장되었는가?'],
        conclusion: '세 가지가 확인되면 녹화를 시작하세요.',
      },
      motionSequence: [
        { step: 1, atMs: 0, action: 'item1' },
        { step: 2, atMs: 1500, action: 'item2' },
        { step: 3, atMs: 3000, action: 'item3' },
        { step: 4, atMs: 5000, action: 'conclusion' },
      ],
      interaction: { mode: 'CLICK' },
      sound: ['pop', 'pop', 'pop', 'success'],
    },
  ],
};

export const SAMPLE_PROJECT_JSON = JSON.stringify(SAMPLE_PROJECT, null, 2);
